In [4]:
import pandas as pd

saramin_df = pd.read_csv('saramin_df.csv', encoding='utf-8')
saramin_df

,회사명,직무,링크,공고내용,회사주소
0,(주)이음인터렉티브,데이터 사이언티스트,https://www.saramin.co.kr/zf_user/jobs/relay/v...,2023 신규채용\n# 데이터사이언티스트\n# 데이터엔지니어 \n㈜이음인터렉티브는 ...,"(06621) 서울 서초구 강남대로 369, 12층\n신분당선 강남역에서 200m 이내"
1,데이콘(주),데이터 사이언티스트,https://www.saramin.co.kr/zf_user/jobs/relay/v...,데이터 사이언티스트 인턴 채용(채용 시 조기 마감)\n\n\n\n\n모집부문 및 상...,"(07237) 서울 영등포구 은행로 3 익스콘벤처타워, 901호(여의도동)\n서울 ..."
2,(주)위키드스톰,데이터 사이언티스트,https://www.saramin.co.kr/zf_user/jobs/relay/v...,데이터 사이언티스트 경력직 채용\n\n\n\n\n모집부문 및 상세내용\n데이터 사이...,(07788) 서울 강서구 마곡중앙로 161-8 두산더랜드파크 8층 819호(마곡동...
3,(주)카비,데이터 사이언티스트,https://www.saramin.co.kr/zf_user/jobs/relay/v...,"◆ CARVI News\n\n[ZDNet Korea] 카비-교통장애인협회, AI로 ...",(153-788) 서울 금천구 가산동 벽산디지털밸리5차 301호
4,(주)핀커스코리아,데이터 사이언티스트,https://www.saramin.co.kr/zf_user/jobs/relay/v...,[기업소개] \n- 이커머스에 특화된 AI/빅데이터 플랫폼 기업\n- 차별화 된 비...,(135-080) 서울 강남구 역삼동 736-42 예동빌딩 8층\n서울 2호선 역삼...
...,...,...,...,...,...
2374,(주)케이티넥스알,데이터 엔지니어,https://www.saramin.co.kr/zf_user/jobs/relay/v...,[KT NexR] 백엔드 개발자 채용\n서비스 소개\nkt NexR은 수년 전부터 ...,None
2375,롯데헬스케어(주),데이터 엔지니어,https://www.saramin.co.kr/zf_user/jobs/relay/v...,"웹 프론트 엔지니어\n서비스 소개\n""Every Moment of your Heal...",(07293) 서울 영등포구 문래북로 116 트리플렉스 403호\n서울 2호선 문래...
2376,(주)제이슨그룹,데이터 엔지니어,https://www.saramin.co.kr/zf_user/jobs/relay/v...,[제이슨그룹]백엔드 개발자\n서비스 소개\n데이터 기반 서비스 플랫폼 개발 및 운영...,"(06232) 서울 강남구 테헤란로2길 21, 12층-14층\n신분당선 강남역에서 ..."
2377,(주)오투플러스,데이터 엔지니어,https://www.saramin.co.kr/zf_user/jobs/relay/v...,[O2pluss] Back-end 개발자 추가 모집\n서비스 소개\n'고객과 배송을...,(153-795) 서울 금천구 가산동 가산디지털1로 128 에스티엑스브이타워 10층...
2378,주식회사 마이너,데이터 엔지니어,https://www.saramin.co.kr/zf_user/jobs/relay/v...,[MiNER] 서버 개발자\n서비스 소개\n안녕하세요? 데이터 테크 스타트업 MiN...,"(06232) 서울 강남구 테헤란로2길 21, 12층-14층\n신분당선 강남역에서 ..."